export const LIMITS = {
  MAX_WEIGHT_GRAMS: 50000,
  MAX_CALORIES: 10000,
  MAX_MACRO_GRAMS: 1000,
  MAX_PORTIONS: 100,
  MAX_RECIPE_INGREDIENTS: 50,
  MAX_RECIPE_NAME_LENGTH: 100,
  MAX_CALCULATION_NAME_LENGTH: 100,
  MAX_TAG_LENGTH: 30,
  MAX_TAG_COUNT: 10,
  MACRO_CALORIE_WARNING_THRESHOLD_PERCENT: 20,
} as const;
