-- Initial schema for Meal Prep Companion.
-- Design decisions:
-- - UUID primary keys everywhere (generated by the database or the client).
-- - user_id references auth.users(id) for Row-Level Security ownership.
-- - updated_at is managed by a trigger (moddatetime extension or manual trigger).
-- - Derived nutrition (batch totals, per-portion, yield ratios) is NEVER persisted.
-- - Tags are stored as a text[] array — the simplest Postgres representation.
-- - Normalised ingredient names are unique per user to prevent duplicates.
-- - meal_plan_entries use a simple meal_slot text with check constraint.
-- - data_migrations tracks which migration keys have been applied per user.

-- Enable extensions
create extension if not exists "uuid-ossp";

-- ============================================================================
-- updated_at trigger
-- ============================================================================
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ============================================================================
-- ingredients
-- ============================================================================
create table ingredients (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  normalized_name text not null,
  calories_per_100g real not null check (calories_per_100g >= 0),
  protein_per_100g real not null check (protein_per_100g >= 0),
  carbs_per_100g real not null default 0 check (carbs_per_100g >= 0),
  fat_per_100g real not null default 0 check (fat_per_100g >= 0),
  category text,
  notes text,
  source text check (source in ('starter', 'custom')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint unique_normalized_name_per_user unique (user_id, normalized_name)
);

create trigger ingredients_updated_at
  before update on ingredients
  for each row execute function set_updated_at();

create index idx_ingredients_user_id on ingredients(user_id);
create index idx_ingredients_normalized_name on ingredients(user_id, normalized_name);

-- ============================================================================
-- recipes
-- ============================================================================
create table recipes (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  portions integer not null check (portions > 0),
  notes text not null default '',
  tags text[] not null default '{}',
  favourite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger recipes_updated_at
  before update on recipes
  for each row execute function set_updated_at();

create index idx_recipes_user_id on recipes(user_id);
create index idx_recipes_user_favourite on recipes(user_id, favourite);
create index idx_recipes_user_updated on recipes(user_id, updated_at desc);

-- ============================================================================
-- recipe_ingredients
-- ============================================================================
create table recipe_ingredients (
  id uuid primary key default uuid_generate_v4(),
  recipe_id uuid not null references recipes(id) on delete cascade,
  ingredient_id uuid not null references ingredients(id) on delete restrict,
  quantity_grams real not null check (quantity_grams > 0),
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index idx_recipe_ingredients_recipe on recipe_ingredients(recipe_id);
create index idx_recipe_ingredients_ingredient on recipe_ingredients(ingredient_id);

-- ============================================================================
-- dry_to_cooked_calculations
-- ============================================================================
create table dry_to_cooked_calculations (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  ingredient_id uuid references ingredients(id) on delete set null,
  dry_weight real not null check (dry_weight > 0),
  cooked_weight real not null check (cooked_weight > 0),
  calories_per_100g real not null check (calories_per_100g >= 0),
  protein_per_100g real not null check (protein_per_100g >= 0),
  carbs_per_100g real not null default 0 check (carbs_per_100g >= 0),
  fat_per_100g real not null default 0 check (fat_per_100g >= 0),
  nutrition_basis real not null default 100 check (nutrition_basis >= 1),
  portions integer not null default 1 check (portions > 0),
  dry_serving_weight real not null default 0 check (dry_serving_weight >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger dry_to_cooked_calculations_updated_at
  before update on dry_to_cooked_calculations
  for each row execute function set_updated_at();

create index idx_dry_to_cooked_user_id on dry_to_cooked_calculations(user_id);

-- ============================================================================
-- meal_plan_entries
-- ============================================================================
create table meal_plan_entries (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_id uuid not null references recipes(id) on delete cascade,
  planned_date date not null,
  meal_slot text not null check (meal_slot in ('breakfast', 'lunch', 'dinner', 'snack')),
  servings integer not null default 1 check (servings > 0),
  notes text,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger meal_plan_entries_updated_at
  before update on meal_plan_entries
  for each row execute function set_updated_at();

create index idx_meal_plan_user_date on meal_plan_entries(user_id, planned_date);
create index idx_meal_plan_recipe on meal_plan_entries(recipe_id);

-- ============================================================================
-- data_migrations
-- ============================================================================
create table data_migrations (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  migration_key text not null,
  applied_at timestamptz not null default now(),

  constraint unique_user_migration_key unique (user_id, migration_key)
);

create index idx_data_migrations_user on data_migrations(user_id);
